export const ADD_INGREDIENTS = "ADD_INGREDIENTS";
export const ADD_TO_CONSTRUCTOR = "ADD_TO_CONSTRUCTOR";
export const REMOVE_FROM_CONSTRUCTOR = "REMOVE_FROM_CONSTRUCTOR";
export const CLEAR_CONSTRUCTOR = "CLEAR_CONSTRUCTOR";
export const SAVE_ORDER_NUMBER = "SAVE_ORDER_NUMBER";
